### ISSUE TITLE
Support @JsonProperty to retrieve name for propertyPath

### ISSUE THREAD

**Issue by dutrieux** [officiallysingh/spring-boot-problem-handler#5]
In my Model (or DTO) I use 
```java
@JsonProperty("surname")
@NotBlank
String lastname,
```
 to change the property name

And when `MethodArgumentNotValidException` fire (with @Valid on property of rest method), the propertyPath value of violations is not correct : I have the name of property bean not the name of JsonProperty

![image](https://github.com/officiallysingh/spring-boot-problem-handler/assets/1622751/0f82c5e9-79c8-4282-b8b0-af6841d2a819)

I workaround by create `MyWebExceptionHandler` class that `extends WebExceptionHandler` and override method public `ViolationVM handleFieldError(final FieldError fieldError, final Throwable exception)` ([MyWebExceptionHandler.zip](https://github.com/officiallysingh/spring-boot-problem-handler/files/14267712/MyWebExceptionHandler.zip)).

**Comment by officiallysingh** [comment]
Yeah, that would work for your scenario as you can customize all default advices.

**Comment by officiallysingh** [comment]
I have added this use case and the custom advice provided by you in documentation
